/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movimientoletra;

import java.awt.Graphics;

/**
 *
 * @author Fran
 */
public class PanelLetra extends javax.swing.JPanel {

    /**
     * Creates new form PanelLetra
     */
    public int cont;
    public boolean avanzar;
    public boolean interrumpir;
    
    public PanelLetra() {
        initComponents();
        lblLetra.setLocation(1,100);
        cont=0;   
        HiloMovimiento h1=new HiloMovimiento(this);
        new Thread(h1).start();
        interrumpir=false;
        avanzar=true;
    }
    
    public void paint(Graphics g){
        super.paint(g);
        lblLetra.setLocation(cont,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAccion = new javax.swing.JButton();
        lblLetra = new javax.swing.JLabel();

        btnAccion.setText("Finalizar Hilo");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });

        lblLetra.setText("O");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnAccion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(lblLetra)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnAccion)
                .addGap(50, 50, 50)
                .addComponent(lblLetra)
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        if(interrumpir==false){
            btnAccion.setText("Reiniciar");
            interrumpir=true;
            
        }else{
            btnAccion.setText("Finalizar hilo");
            HiloMovimiento h1=new HiloMovimiento(this);
            new Thread(h1).start();
            interrumpir=false;
        }
    }//GEN-LAST:event_btnAccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JLabel lblLetra;
    // End of variables declaration//GEN-END:variables
}
